name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grbl2:$(date +%s)

    - name: Test running
      uses: docker://alpine
      with:
        entrypoint: /bin/sh
        args: -i --rm --name grbl2-running grbl2

    - name: Upload source code artifact
      uses: actions/upload-artifact@v2
      with:
        name: source-code
        path: .  # 指定要上传的源代码路径，这里假设源代码位于根目录下
