name: Docker Image CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grbl2:$(date +%s)

    - name: Test runing
    - run: docker run -it --rm --name grbl2-running grbl2
