name: CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grbl2:$(date +%s)

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.7

    - name: Install pyinstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test running
      run: |
        cp bot_config.yaml grbl_config.yaml
        timeout 120s python ./bot.py  # 尝试运行60s后退出
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "Python程序出错: （在60s内退出）请检查输出的信息 $exit_code"
          exit $exit_code
        else
          echo "Python程序测试完成！ (在规定时间内没有退出） "
          exit 0
        fi

    - name: Upload source code artifact
      uses: actions/upload-artifact@v2
      with:
        name: source-code
        path: .  # 上传根目录所有文件
